#!/bin/bash

keyfile="$HOME/.chatgpt-key"

if [ ! -f "$keyfile" ]; then
    echo "Error: File '$keyfile' does not exist."
    exit 1
fi

API_KEY="$(cat $keyfile)"

if [ $# -eq 0 ]; then
    echo "Error: No arguments provided."
    echo "Usage: ,gpt <arg1> [arg2 ...]"
    exit 1
fi

stdin=''

if [ ! -t 0 ]; then
    stdin="$(cat)"  # Read all stdin into the variable
fi

# model='gpt-3.5-turbo'
default_model='gpt-4o'
model="${GPT_MODEL:-$default_model}"


args="$*"

history_file="$HOME/.gpt-history"
last_gpt_answer_file="$HOME/.gpt-last-conv"

data=$(jq -Rn --arg input "$args $stdin" '{
    "model": "'"$model"'",
    "messages": [{"role": "user", "content": $input}]
  }')

echo "$data" >> $history_file
echo "" >> $history_file

echo "$data" > $last_gpt_answer_file
echo "" >> $last_gpt_answer_file

output=$(curl -s https://api.openai.com/v1/chat/completions \
  -H "Authorization: Bearer $API_KEY" \
  -H "Content-Type: application/json" \
  -d "$data")

resp=$(echo "$output" | jq -r '.choices[0].message.content')

if [ "$resp" = "null" ]; then
    echo "$output"
    exit 1
fi

echo "$resp" | tee -a $history_file | tee -a $last_gpt_answer_file

echo "" >> $history_file
echo "" >> $history_file


