#!/bin/sh
cmd_file=$(command -v "$1")

scripts_dir="$HOME/scripts"
new_file="$scripts_dir/$1";

if [ -z "$1" ]; then
    echo "Error: \$1 is empty. Exiting script."
    exit 1
fi

if test -n "$cmd_file";
then
  echo "script $1 already exists at $cmd_file"
elif [ ! -f $new_file ]
then
  echo "creating $new_file";
  nvim "$new_file" && chmod +x "$new_file";
fi


