[font]
size = 10

[font.normal]
# family = "FiraCode Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "Iosevka"
family = "Monaco Nerd Font"

[window]
decorations = "buttonless"
# blur = true
# opacity = 0.79
# opacity = 0.90
opacity = 0.975
option_as_alt = "Both"
# startup_mode = "Maximized"

[window.padding]
x = 6
y = 4

[window.position]
x = 4
y = 4

# [env]
# necessary to support true color in tmux
# TERM = "alacritty-direct"
# TERM = "xterm-256color"
# [shell]
# program = "/opt/homebrew/bin/tmux"
