[font]
size = 18

[font.normal]
#family = "FiraCode Nerd Font"
#family = "JetBrainsMono Nerd Font"
# family = "Iosevka"
# family = "Monaco Nerd Font"
# family = "Source Code Pro"
family = "iA Writer Mono V"
#family = "DejaVu Sans Mono"
# family = "Anonymous Pro"

[window]
decorations = "buttonless"
# blur = true
# opacity = 0.79
# opacity = 0.90
opacity = 0.975
#option_as_alt = "Both" # breaks "polish" signs
# startup_mode = "Maximized"

[window.padding]
x = 6
y = 4

[window.position]
x = 40
y = 40

[window.dimensions]
columns = 132
lines = 36

# [env]
# necessary to support true color in tmux
# TERM = "alacritty-direct"
# TERM = "xterm-256color"
# [shell]
# program = "/opt/homebrew/bin/tmux"
