

[font]
size = 16

[font.normal]
# family = "FiraCode Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "Iosevka"
family = "Monaco Nerd Font"

[window]
decorations = "buttonless"
# blur = true
# opacity = 0.5
option_as_alt = "Both"

[window.padding]
x = 4
y = 0

# [env]
# necessary to support true color in tmux
# TERM = "alacritty-direct"
# TERM = "xterm-256color"
